nabhold/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.PostListView.as_view(), name='articles'),
    path('posts/', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]

nabhold/books/urls.py
import imp
from django.urls import path, re_path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list')
]

nabhold/bookstore/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books_index, name='home'),
    path('books/', views.BookListView.as_view(), name='book_list'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book_detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my_borrowed'),
    path('books/all-borrowed/', views.AllLoanedBooksListView.as_view(), name='all_borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author_detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    ]

nabhold/nabhold/urls.py
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings 


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('catalog/', include('books.urls', namespace='books')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('store/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},  name='django.contrib.sitemaps.views.sitemap'),
    path('', include('core.urls', namespace='main')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nabhold/books/models.py
from django.contrib.auth.models import User
from datetime import date
import uuid
from django.db import models
from django.urls import reverse  # To generate URLS by reversing URL patterns
# Create your models here.


class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    genre_id = models.PositiveIntegerField(primary_key=True, default=100)
    name = models.CharField(
        max_length=200,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in file.
    bookshot = models.ImageField(
        upload_to='book_bookshots', blank=True, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    total_pages = models.PositiveIntegerField(default=0)
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)
    rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    publisher = models.ForeignKey(
        to=Publisher, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'publisher']

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('bookstore:book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.book.title)


class Author(models.Model):
    """Model representing an author."""
    SALUTATION = (
        ('MR', 'Master'),
        ('MS', 'Miss'),
        ('PROF', 'Professor'),
        ('REV', 'Reverand'),
        ('DR', 'Doctor'),
    )
    salutation = models.CharField(max_length=10, choices=SALUTATION, blank=True,
                                  default='MR', help_text='Your prefered title for salutation')
    first_name = models.CharField(max_length=100)
    initials = models.CharField(max_length=2, null=True, blank=True)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)
    last_update = models.DateTimeField(auto_now=True)
    headshot = models.ImageField(
        upload_to='author_headshots', blank=True, null=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)

nabhold/books/forms.py
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms

from . models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal date in the past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal date is more than 3 weeks ahead'))
        return data


class RenewBookModelForm(forms.ModelForm):
    def clean_due_back(self):
            data = self.cleaned_data['due_back']
            # Check if a date is not in the past.
            if data < datetime.date.today():
                raise ValidationError(_('Invalid date - renewal in past'))

            # Check if a date is in the allowed range (+4 weeks from today).
            if data > datetime.date.today() + datetime.timedelta(weeks=4):
                raise ValidationError(
                    _('Invalid date - renewal more than 4 weeks ahead'))
            # Remember to always return the cleaned data.
            return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _( 'Enter a date between now and 4 weeks (default 3).')}

nabhold/bookstore/forms.py
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django import forms

from . models import BookInstance 


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal date in the past'))
        
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal date is more than 3 weeks ahead'))
        return data

class RenewBookModelForm(forms.ModelForm):
        def clean_due_back(self):
            data = self.cleaned_data['due_back']
            # Check if a date is not in the past.
            if data < datetime.date.today():
                raise ValidationError(_('Invalid date - renewal in past'))

            # Check if a date is in the allowed range (+4 weeks from today).
            if data > datetime.date.today() + datetime.timedelta(weeks=4):
                raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
            # Remember to always return the cleaned data.
            return data

        class Meta:
            model = BookInstance
            fields = ['due_back']
            labels = {'due_back': _('New renewal date')}
            help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

nabhold/books/views.py
import datetime
from .models import Book, Author, BookInstance, Genre
from . forms import RenewBookForm, RenewBookModelForm
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from django.shortcuts import render, get_object_or_404


class BookListView(generic.ListView):
    pass

nabhold/bookstore/views.py
import datetime 
from .models import Book, Author, BookInstance, Genre
from . forms import RenewBookForm, RenewBookModelForm
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView 
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect  
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from django.shortcuts import render, get_object_or_404 

# Create your views here. 




def books_index(request, template = 'book/book-home.html'):
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_genres = Genre.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    # Available copies of books
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()
    num_books_title_word_available = Book.objects.filter(
        title__icontains='a').count()
    num_authors = Author.objects.count()  # The 'all()' is implied by default.
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1

    #set the context
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
        'num_genres': num_genres,
        'num_books_title_word_available': num_books_title_word_available,
         }

    return render(request, template, context = context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

    # your own name for the list as a template variable
    context_object_name = 'books'
    queryset = Book.objects.all()  # Get 5 books containing the title war
    # Specify your own template name/location
    template_name = 'book/book_list.html'



class BookDetailView(generic.DetailView):
    model = Book 
    template_name = 'book/book_detail.html'


 
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'book/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class AllLoanedBooksListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    paginate_by: 25
    queryset = BookInstance.objects.filter(
        status__exact='o').order_by('due_back')
    template_name = 'book/all_borrowed_books.html'


@login_required
@permission_required('book.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return HttpResponseRedirect(reverse('all-borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
        context = {'form': form,
                   'book_instance': book_instance, }
        return render(request, 'book/book_renew_librarian.html', context)



class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 25

    # your own name for the list as a template variable
    context_object_name = 'authors'
    queryset = Book.objects.all()  # Get 5 books containing the title war
    # Specify your own template name/location
    template_name = 'book/author_list.html'



class AuthorDetailView(generic.DetailView):
    model = Author 
    template_name = 'book/author_detail.html'


 
class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '11/06/2020'}
    template_name = 'book/author_form.html'


 
class AuthorUpdate(UpdateView):
    model = Author
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'
    template_name = 'book/author_form.html'

 
class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

nabhold/bookstore/templates/book/all_borrowed_books.html
{% extends "book/book-base.html" %}

{% block content %}
<div class="container">
    <h1>Books on Loan</h1>

    {% if bookinstance_list %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">Cover</th>
                <th scope="col">Book Title</th>
                <th scope="col">Author </th>
                <th scope="col">Borrowed By </th>
                <th scope="col">Due Date </th>
            </tr>
        </thead>
        <tbody>
            {% for bookinst in bookinstance_list %}
            <tr>
                <th scope="row">{{bookinst.book.bookshot}}</th>
                <td><a href="{% url 'bookstore:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> </td>
                <td>{{ bookinst.book.author.first_name }} {{ bookinst.book.author.initials }} {{bookinst.book.author.last_name}} </td>
                <td>{{ bookinst.borrower.first_name }} {{ bookinst.borrower.last_name }}</td>
                <td class="{% if bookinst.is_overdue %}text-danger {% else %} text-success {% endif %}" >{{ bookinst.due_back }}
                    {% if perms.catalog.can_mark_returned %}- <a href="{% url 'bookstore:renew-book-librarian' bookinst.id %}">Renew</a> {% endif %}
                </td>
            </tr> 
            {% endfor %}
        </tbody>
            
    </table>

    {% else %}
    <p>There are no books borrowed.</p>
    {% endif %}
    {% include "pagination.html" with page=page_obj %}
</div>
{% endblock %}

nabhold/bookstore/templates/book/author_confirm_delete.html
{% extends "book/book-base.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

nabhold/bookstore/templates/book/author_form.html
{% extends "book/book-base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
    </div>
</section>
{% endblock %}

nabhold/bookstore/templates/book/author_list.html
{% extends "book/book-base.html" %}
{% block bootstrap5_title %} Authors {% endblock %}
{% load static %}
<!-- Theme CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

{% block content %}
<div class="container">
    <h1>List of Authors</h1>
    {% if authors %}
    <ul>
        {% for author in authors %}
        <li>
            <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{author.last_name }}</a> ({{author.salutation }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no books in the library with this title. </p>
    {% endif %}
    {% include "pagination.html" with page=page_obj %}
</div>
{% endblock %}

nabhold/bookstore/templates/book/book-base.html
{% extends "base.html" %}
{# Load the tag library #}
{% load static bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


<!DOCTYPE html>
<html lang="en">

<head>
    
    
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Webestica.com">
    <meta name="description" content="Bootstrap based News, Magazine and Blog Theme">
    {% block bootstrap5_title %} Books, Blog and Magazine {% endblock %} 
   
    <!-- Theme CSS -->
</head>

<body> 
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                {% block sidebar %} {% endblock %}
            </div>
            <div class="col-lg-8">
                {% block content %} {% endblock %}
                {% block pagination %} {% endblock %}
            </div>
        </div>
    </div>
{% block after_content %}
<section class="section">
    <div class="container">
        <!-- Widgets START -->
        <div class="row pt-5">
            <!-- Footer Widget -->
            <div class="col-md-6 col-lg-4 mb-4">
                <img class="light-mode-item" src="assets/images/logo.svg" alt="logo">
                <img class="dark-mode-item" src="assets/images/logo-light.svg" alt="logo">
                <p class="mt-3">The next-generation blog, news, and magazine theme for you to start sharing your
                    stories today! This Bootstrap 5 based theme is ideal for all types of sites that deliver the
                    news.</p>
                <div class="mt-4">©2022 <a href="https://www.webestica.com/" class="text-reset btn-link"
                        target="_blank">Webestica</a>. All rights reserved
                </div>
            </div>
    
            <!-- Footer Widget -->
            <div class="col-md-6 col-lg-3 mb-4">
                <h5 class="mb-4">Navigation</h5>
                <div class="row">
                    <div class="col-6">
                        <!-- Item -->
                        <ul class="nav flex-column">
                            <li class="nav-item"><a class="nav-link pt-0" href="#">Features</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Style Guide</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Contact us</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Get Theme</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Support</a></li>
                        </ul>
                    </div>
                    <div class="col-6">
                        <!-- Item -->
                        <ul class="nav flex-column">
                            <li class="nav-item"><a class="nav-link pt-0" href="#">News</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Career <span
                                        class="badge text-bg-danger ms-2">2 Job</span></a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Technology</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Startups</a></li>
                            <li class="nav-item"><a class="nav-link" href="#">Gadgets</a></li>
                        </ul>
                    </div>
                </div>
            </div>
    
            <!-- Footer Widget -->
            <div class="col-sm-6 col-lg-3 mb-4">
                <h5 class="mb-4">Browse by Tag</h5>
                <!-- Item -->
                <ul class="list-inline">
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-primary-soft">Travel</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-warning-soft">Business</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-success-soft">Tech</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-danger-soft">Gadgets</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-info-soft">Lifestyle</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-primary-soft">Vaccine</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-warning-soft">Marketing</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-success-soft">Sports</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-danger-soft">Covid-19</a></li>
                    <li class="list-inline-item"><a href="#" class="btn btn-sm btn-info-soft">Politics</a></li>
                </ul>
            </div>
    
            <!-- Footer Widget -->
            <div class="col-sm-6 col-lg-2 mb-4">
                <h5 class="mb-4">Our Social handles</h5>
                <!-- Item -->
                <ul class="nav flex-column">
                    <li class="nav-item"><a class="nav-link pt-0" href="#"><i
                                class="fab fa-facebook-square fa-fw me-2 text-facebook"></i>Facebook</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i
                                class="fab fa-twitter-square fa-fw me-2 text-twitter"></i>Twitter</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i
                                class="fab fa-linkedin fa-fw me-2 text-linkedin"></i>Linkedin</a></li>
                    <li class="nav-item"><a class="nav-link" href="#"><i
                                class="fab fa-youtube-square fa-fw me-2 text-youtube"></i>YouTube</a></li>
                </ul>
            </div>
        </div>
        <!-- Widgets END -->
    </div>
</section>
{% endblock %}
{% block bootstrap5_extra_script %}
    <!-- =======================
JS libraries, plugins and custom scripts -->

    <!-- Bootstrap JS -->
    <script src="assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Vendors -->
    <script src="assets/vendor/tiny-slider/tiny-slider.js"></script>
    <script src="assets/vendor/glightbox/js/glightbox.js"></script>

    <!-- Template Functions -->
    <script src="assets/js/functions.js"></script>
{% endblock %}
</body>

</html>

nabhold/bookstore/templates/book/book-home.html
{% extends "book/book-base.html" %}
{% block title %} Books Home {% endblock %}
{% load static %}

{% block sidebar%}
<ul>
    <li><a href="{% url 'books:books-home' %}">Home</a></li>
    <li><a href="{% url 'books:books' %}">All books</a></li>
    <li><a href="{% url 'books:all-borrowed' %}">Books on loan</a></li>
    <li><a href="{% url 'books:author-list' %}">All authors</a></li>
</ul>
{% endblock %}

{% block content %}

<section class="section">
    <div class="container">
        <h2>Dynamic content</h2>
        
        <p>The library has the following record counts:</p>
        <ul>
            {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'books:my-borrowed' %}">My Borrowed</a></li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
        </ul>
        <ul>
            <li><strong>Books:</strong> {{ num_books }}</li>
            <li><strong>Copies:</strong> {{ num_instances }}</li>
            <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
            <li><strong>Authors:</strong> {{ num_authors }}</li>
        </ul>
        <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
    </div>

   

</section>
{% endblock %}

nabhold/bookstore/templates/book/book_detail.html
{% extends "book/book-base.html" %}

{% block content %}
<div class="container">
    <h1>Title: {{ book.title }}</h1>
    
    <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
    <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

</div>
<div class="container">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
    </p>
    {% if copy.status != 'a' %}
    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

nabhold/bookstore/templates/book/book_list.html
{% extends "book/book-base.html" %}
{% block title %} Books list {% endblock %}
{% load static %} 

{% block content %}
<div class="container">
   <h1>Book List</h1>
   {% if books %}
   <ul>
      {% for book in books %}
      <li>
         <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}
   </ul>
   {% else %}
   <p>There are no books in the library with this title. </p>
   {% endif %}
   {% include "pagination.html" with page=page_obj %}
</div>
{% endblock %}

nabhold/bookstore/templates/book/book_renew_librarian.html
{% extends "book/book-base.html" %}

{% block content %}
<section class="section">
    <div class="container">
        <h1>Renew: {{ book_instance.book.title }}</h1>
        <p>Borrower: {{ book_instance.borrower }}</p>
        <p{% if book_instance.is_overdue %} class="text-danger" {% endif %}>Due date: {{ book_instance.due_back }}</p>
        
            <form action="" method="post">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Submit">
            </form>
    </div>
</section>
{% endblock %}

nabhold/bookstore/templates/book/bookinstance_list_borrowed_user.html
{% extends "book/book-base.html" %}

{% block content %}
    <div class="container">
        <h1>Borrowed books</h1>
        
        {% if bookinstance_list %}
        <ul>
        
            {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'bookstore:book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
            </li>
            {% endfor %}
        </ul>
        
        {% else %}
        <p>There are no books borrowed.</p>
        {% endif %}
    </div>
{% endblock %}