nabhold/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.PostListView.as_view(), name='articles'),
    path('posts/', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]

nabhold/nabhold/urls.py
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings 


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('catalog/', include('books.urls', namespace='books')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('store/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},  name='django.contrib.sitemaps.views.sitemap'),
    path('', include('core.urls', namespace='main')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nabhold/blog/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    summary = models.CharField(max_length=1000, blank=True, null=True)

    photo = models.ImageField(upload_to='blogs/%Y/%m/%d/', blank=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

    def get_absolute_url(self):
        return reverse('blog:post_share', args=[self.post])

nabhold/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control border border-primary rounded-0'}),
            'email': forms.EmailInput(attrs={'class': 'form-control border border-primary rounded-0'}),
            'body': forms.Textarea(attrs={'class': 'form-control border border-primary rounded-0'})
        }


class SearchForm(forms.Form):
    query = forms.CharField()

nabhold/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.views import generic
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector, SearchVectorField, SearchQuery, SearchRank, TrigramSimilarity
from taggit.models import Tag
from django.db.models import Count, Max, Avg, Min


def post_list(request, tag_slug = None):
    
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 12)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'posts/posts.html',
                  {'posts': posts, 'tag':tag})



def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'posts/post_detail.html',
                  {'post': post,
                   'comments': comments,
                   'form': form,
                   'similar_posts': similar_posts})



class PostListView(generic.ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 12
    template_name = 'posts/post_list.html'


@login_required
def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id,
                             status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'info@nabhold.com',
                      [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'posts/post_share.html', {'post': post, 'form': form, 'sent': sent})


@require_POST
@login_required
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id,  status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'posts/post_comment.html', {'post': post, 'form': form, 'comment': comment})


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    pass


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    pass


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    pass


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + \
                SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(rank__gte=0.3).order_by('-rank')
    return render(request,
                  'posts/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

nabhold/blog/templates/posts/post_comment.html
{% extends "base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
{% include "includes/comment_form.html" %}
{% endif %}
{% endblock %}

nabhold/blog/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block title %}{{ post.title }}{% endblock %}
{% load static bootstrap5 %}


{% block content %}
<section class="py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5">
            <div class="col-lg-3">
                <div class="d-flex align-items-center mt-lg-5 mb-4">
                    <img class="img-fluid rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg"
                        alt="..." />
                    <div class="ms-3">
                        <div class="fw-bold"> {{ post.author.first_name |capfirst }} {{ post.author.last_name |capfirst }} </div>
                        <div class="text-muted">{{ post.tags.all|join:", " }} </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <!-- Post content-->
                <article>
                    <!-- Post header-->
                    <header class="mb-4">
                        <!-- Post title-->
                        <h3 class="fw-bolder mb-1">{{ post.title }}</h3>
                        <!-- Post meta content-->
                        <div class="text-muted fst-italic mb-2">Published {{ post.publish | date:"l d F Y" }} by {{ post.author.first_name |capfirst }} {{ post.author.last_name |capfirst }} </div>
                        <!-- Post categories-->
                        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                        <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                    </header>
                    <!-- Preview image figure-->
                    <figure class="mb-4"><img class="img-fluid rounded"
                            src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                    <!-- Post content-->
                    <section class="mb-5">
                        {{ post.body|linebreaks }}
                    </section>
                </article>
                <div>
                    <p>
                        <a href="{% url 'blog:post_share' post.id %}">
                            Share this post
                        </a>
                    </p>
                    {% with comments.count as total_comments %}
                    <h4>
                        {{ total_comments }} comment{{ total_comments|pluralize }}
                    </h4>
                    {% endwith %}
                </div>
                <!-- Comments section-->
                <section>
                    <div class="card bg-light">
                        <div class="card-body">
                            {% if request.user.is_authenticated %}
                            <!-- Comment form-->
                            {% include "includes/comment_form.html" %} 
                            {%else%}
                            <p> You need to be logged in to post a comment. click <a href="{% url 'account:login' %}">here</a> to login </p>
                            {% endif %}

                            {% for comment in comments %}
                            <div class="d-flex mb-4">
                                <!-- Parent comment-->
                                <div class="flex-shrink-0">
                                    <img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                                </div>
                                <div class="ms-3">
                                    <div class="fw-bold">{{ comment.name }}</div>
                                        {{ comment.body|linebreaks }}
                                    <!-- Child comment 1 
                                    <div class="d-flex mt-4">
                                        <div class="flex-shrink-0"><img class="rounded-circle"
                                                src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                                        </div>
                                        <div class="ms-3">
                                            <div class="fw-bold">  {{ comment.name }}

                                        </div> 
                                            {{ comment.body|linebreaks }}
                                        </div>
                                    </div> -->
                                </div>

                            </div>
                            {% empty %}
                            <p>There are no comments.</p>
                            {% endfor %} 
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
        <h3>Similar posts</h3>
        <hr>
        <div class="row">
        {% for post in similar_posts %}
            <div class="col col-sm-6 col-md-4, col-lg-4">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col col-md-4">
                            <img src="..." class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col col-md-8">
                            <div class="card-body">
                                <p class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </p> 
                                <p class="card-text"><small class="text-muted">{{ post.publish }}</small></p>
                            </div>
                        </div>
                    </div>
                </div> 
                
            </div>

        {% empty %}
        There are no similar posts yet.
        {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

nabhold/blog/templates/posts/post_list.html
{% extends 'base.html' %}


{% block title %}My Blog{% endblock %}
{% load static bootstrap5 %}


{% block content %}
<!-- Page Content-->
<section class="py-5">
    <div class="container px-5"> 
        <div class="card border-0 rounded-0 overflow-hidden">
            <div class="card-body p-0">
                <div class="row gx-0">
                    {% for post in posts|slice:":1" %}
                    <div class="col col-lg-6 col-xl-5 py-lg-5">
                        <div class="p-4 p-md-5 bg-white">
                            <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                            <h3 class="h3 fw-bolder">{{ post.title }}</h3>
                            <p>{{post.body |truncatewords:20 | linebreaks }}</p>
                            <a class="stretched-link text-decoration-none" href="{{ post.get_absolute_url }}">
                                Read more
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="col col-lg-6 col-xl-7">
                        <div class="bg-featured-blog"
                            style="background-image: url('https://dummyimage.com/700x350/343a40/6c757d')">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

 
<section class="py-5 bg-light">
    <div class="container-fluid px-5">
        <div class="row gx-5">
            <div class="col col-md-6 col-lg-7 col-xl-8">
                <h2 class="fw-bolder fs-5 mb-4">Tech News</h2>
                <div class="list-group mb-4">
                {% for post in posts|slice:":5" %} 
                    <a class="list-group-item list-group-item-action d-flex align-items-center w-100 h6" href="{{ post.get_absolute_url }}">
                        <div class="d-flex align-items-center">
                            <div class="py-2 px-3 mr-2 text-center">
                                <span class="d-block h4 mb-0">{{ post.publish | date:"d" }}</span>
                                <span class="text-small">{{ post.publish | date:"M Y" }}</span>
                            </div>
                            <span class="mb-0 h5 text-primary">{{ post.title }}</span>
                        </div>
                    </a> 
                {% endfor %} 
                </div>
                <div class="text-end mb-5 mb-xl-0">
                    <a class="text-decoration-none" href="{% url 'blog:post_list' %}">
                        More news
                        <i class="bi bi-arrow-right"></i>
                    </a>
                </div>
            </div>
            <div class="col col-md-6 col-lg-5 col-xl-4">
                <div class="card border-0 h-100 bg-white shadow">
                    <div class="card-body p-4">
                        <div class="d-flex h-100 align-items-center justify-content-center">
                            <div class="text-center">
                                <div class="h6 fw-bolder">Contact</div>
                                <p class="text-primary mb-4">
                                    For press inquiries, email us at
                                    <br />
                                    <a href="#!">press@nabhold.com</a>
                                </p>
                                <div class="h6 fw-bolder">Follow us</div>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-twitter"></i></a>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-facebook"></i></a>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-linkedin"></i></a>
                                <a class="fs-5 px-2 link-dark" href="#!"><i class="bi-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="h2 d-block mb-4">Dedicated to high quality customer service.</span>
                <ul class="list-group">
                    <li class="list-group-item bg-transparent px-0">
                        <div class="d-flex align-items-center">
                            <img src="assets/img/icons/icon09.svg" alt="assets/img/icons/icon09.svg"
                                class="icon d-block mr-3">
                            <span class="mb-0 h6">Fully Responsive</span>
                        </div>
                    </li>
                    <li class="list-group-item bg-transparent px-0">
                        <div class="d-flex align-items-center">
                            <img src="assets/img/icons/icon32.svg" alt="assets/img/icons/icon32.svg"
                                class="icon d-block mr-3">
                            <span class="mb-0 h6">Stellar Support</span>
                        </div>
                    </li>
                    <li class="list-group-item bg-transparent px-0">
                        <div class="d-flex align-items-center">
                            <img src="assets/img/icons/icon39.svg" alt="assets/img/icons/icon39.svg"
                                class="icon d-block mr-3">
                            <span class="mb-0 h6">Modular Structure</span>
                        </div>
                    </li>
                    <li class="list-group-item bg-transparent px-0">
                        <div class="d-flex align-items-center">
                            <img src="assets/img/icons/icon40.svg" alt="assets/img/icons/icon40.svg"
                                class="icon d-block mr-3">
                            <span class="mb-0 h6">Stylish Design</span>
                        </div>
                    </li>
                    <li class="list-group-item bg-transparent px-0">
                        <div class="d-flex align-items-center">
                            <img src="assets/img/icons/icon16.svg" alt="assets/img/icons/icon16.svg"
                                class="icon d-block mr-3">
                            <span class="mb-0 h6">Thorough Documenation</span>
                        </div>
                    </li>
                </ul>
            </div>
            {% for post in posts|slice:":2" %}
            <div class="col-md-4 d-flex">
                <div class="card"> 
                    <a href="{{ post.get_absolute_url }}">
                        <img class="card-img-top" src="assets/img/insurance-6.jpg" alt="10 Tips for savvy travellers" />
                    </a>

                    <div class="card-body py-3"> <a href="{{ post.get_absolute_url }}" class="mb-2 d-block">Lifestyle</a>
                        <a href="{{ post.get_absolute_url }}">
                            <h5>{{ post.title}}</h5>
                        </a>

                        <div class="mb-4">
                            <p>{{ post.body | truncatewords:10}}</p>
                        </div>
                    </div> 
                </div>
            </div>
            {% endfor %} 
        </div>
    </div>
</section>

 
<section class="section py-5">
    <div class="container px-5 my-5">
        <!-- Call to action-->
        <aside class="bg-primary bg-gradient rounded-3 p-4 p-sm-5 mt-5">
            <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
                <div class="mb-4 mb-xl-0">
                    <div class="fs-3 fw-bold text-white">New products, delivered to you.</div>
                    <div class="text-white-50">Sign up for our newsletter for the latest updates.</div>
                </div>
                <div class="ms-xl-4">
                    <div class="input-group mb-2">
                        <input class="form-control" type="text" placeholder="Email address..." aria-label="Email address..."
                            aria-describedby="button-newsletter">
                        <button class="btn btn-outline-light" id="button-newsletter" type="button">Sign up</button>
                    </div>
                    <div class="small text-white-50">We care about privacy, and will never share your data.</div>
                </div>
            </div>
        </aside>
    </div>
</section>


<!-- Blog preview section-->
<section class="py-5">
    <div class="container px-5">
        <h2 class="fw-bolder fs-5 mb-4">Recent Articles</h2>
        <div class="row gx-5">
            {% for post in posts %}
            <div class="col col-sm-6 col-md-4 col-lg-3 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/ced4da/6c757d" alt="..." />
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2">News</div>
                        <a class="text-decoration-none link-dark stretched-link" href="{{ post.get_absolute_url}}">
                            <div class="h5 card-title mb-3">{{ post.title }}</div>
                        </a>
                        <p class="card-text mb-0">{{post.body|truncatewords:10|linebreaks }}</p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d"
                                    alt="..." />
                                <div class="small">
                                    <div class="fw-bold">{{post.author.first_name}} {{post.author.lasst_name}}</div>
                                    <div class="text-muted">{{ post.publish|date:"M d, Y"}} &middot; 6 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> 
            {% endfor %}
        </div>
        {% include "pagination.html" with page=page_obj %}
    </div>

</section>

{% endblock %}

nabhold/blog/templates/posts/posts.html
{% extends 'base.html' %}


{% block title %}My Blog{% endblock %}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

<section class="section py-5">
    <div class="container px-5 my-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-8 col-xl-6">
                <div class="text-center">
                    <h2 class="fw-bolder">Blog News &amp; Articles </h2>
                    <p class="lead fw-normal text-muted mb-5">Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                        Eaque fugit ratione dicta mollitia. Officiis ad.</p>
                </div>
            </div>
        </div>
        <div class="row gx-5">
            {% if tag %}
            <h2>Posts tagged with "{{ tag.name }}"</h2>
            {% endif %}
            {% for post in posts %}
            <div class="col-lg-4 mb-5">
                <div class="card h-100 shadow border-0">
                    <img class="card-img-top" src="https://dummyimage.com/600x350/ced4da/6c757d" alt="...">
                    <div class="card-body p-4">
                        <div class="badge bg-primary bg-gradient rounded-pill mb-2 text-sm">{{ post.tags.all|join:", " }}
                        </div>
                        <p class="tags">
                            Tags:
                            {% for tag in post.tags.all %}
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                {{ tag.name }}
                            </a>
                            {% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                        <a class="text-decoration-none link-dark stretched-link" href="{{ post.get_absolute_url }}">
                            <h4 class="card-title mb-3">{{ post.title }}</h4>
                        </a>

                        <p class="card-text mb-0">{{ post.body|truncatewords:10|linebreaks }} </p>
                    </div>
                    <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                        <div class="d-flex align-items-end justify-content-between">
                            <div class="d-flex align-items-center">
                                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d"
                                    alt="...">
                                <div class="small">
                                    <div class="fw-bold">
                                        {{ post.author.first_name|capfirst }} {{ post.author.last_name|capfirst }}
                                    </div>
                                    <div class="text-muted">{{ post.publish }} · 6 min read</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% include "pagination.html" with page=page_obj %}

    </div>
</section>

{% endblock %}

nabhold/blog/templates/posts/search.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}
{% block content %}
<div class="container">
    {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
        {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </h3>
    {% for post in results %}
    <h4>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h4>
     {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
    <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
    {% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
    {% endif %}
</div>
{% endblock %}