nabhold/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # Post views
    path('', views.PostListView.as_view(), name='articles'),
    path('posts/', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('search/', views.post_search, name='post_search'),
]

nabhold/core/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
    path('team/', views.team, name='team'),
    path('about/', views.about, name='about'),
]

nabhold/nabhold/urls.py
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings 


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('catalog/', include('books.urls', namespace='books')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('store/', include('store.urls', namespace='store')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('user/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},  name='django.contrib.sitemaps.views.sitemap'),
    path('', include('core.urls', namespace='main')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nabhold/templates/about.html
{% extends "base.html" %}
{% load static bootstrap5 %}
{% block title %} About Us {% endblock %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}

<div id="banner-area" class="banner-area" style="background-image:url(images/banner/banner1.jpg)">
  <div class="banner-text">
    <div class="container">
        <div class="row">
          <div class="col-lg-12">
              <div class="banner-heading">
                <h1 class="banner-title">About</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                      <li class="breadcrumb-item"><a href="#">Home</a></li>
                      <li class="breadcrumb-item"><a href="#">company</a></li>
                      <li class="breadcrumb-item active" aria-current="page">About Us</li>
                    </ol>
                </nav>
              </div>
          </div><!-- Col end -->
        </div><!-- Row end -->
    </div><!-- Container end -->
  </div><!-- Banner text end -->
</div><!-- Banner area end --> 

<section id="main-container" class="main-container">
  <div class="container">
    <div class="row">
        <div class="col-lg-6">
          <h3 class="column-title">Who We Are</h3>
          <p>when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.</p>
          <blockquote><p>Semporibus autem quibusdam et aut officiis debitis aut rerum est aut optio cumque nihil necessitatibus autemn ec tincidunt nunc posuere ut</p></blockquote>
          <p>He lay on his armour-like  back, and if he lifted. ultrices ultrices sapien, nec tincidunt nunc posuere ut. Lorem ipsum dolor sit amet, consectetur adipiscing elit. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn’t anything embarrassing.</p>

        </div><!-- Col end -->

        <div class="col-lg-6 mt-5 mt-lg-0">
          
          <div id="page-slider" class="page-slider small-bg">

              <div class="item" style="background-image:url(images/slider-pages/slide-page1.jpg)">
                <div class="container">
                    <div class="box-slider-content">
                      <div class="box-slider-text">
                          <h2 class="box-slide-title">Leadership</h2>
                      </div>    
                    </div>
                </div>
              </div><!-- Item 1 end -->

              <div class="item" style="background-image:url(images/slider-pages/slide-page2.jpg)">
                <div class="container">
                    <div class="box-slider-content">
                      <div class="box-slider-text">
                          <h2 class="box-slide-title">Relationships</h2>
                      </div>    
                    </div>
                </div>
              </div><!-- Item 1 end -->

              <div class="item" style="background-image:url(images/slider-pages/slide-page3.jpg)">
                <div class="container">
                    <div class="box-slider-content">
                      <div class="box-slider-text">
                          <h2 class="box-slide-title">Performance</h2>
                      </div>    
                    </div>
                </div>
              </div><!-- Item 1 end -->
          </div><!-- Page slider end-->          
        

        </div><!-- Col end -->
    </div><!-- Content row end -->

  </div><!-- Container end -->
</section><!-- Main container end -->


<section id="facts" class="facts-area dark-bg">
  <div class="container">
    <div class="facts-wrapper">
        <div class="row">
          <div class="col-md-3 col-sm-6 ts-facts">
              <div class="ts-facts-img">
                <img loading="lazy" src="images/icon-image/fact1.png" alt="facts-img">
              </div>
              <div class="ts-facts-content">
                <h2 class="ts-facts-num"><span class="counterUp" data-count="1789">0</span></h2>
                <h3 class="ts-facts-title">Total Projects</h3>
              </div>
          </div><!-- Col end -->

          <div class="col-md-3 col-sm-6 ts-facts mt-5 mt-sm-0">
              <div class="ts-facts-img">
                <img loading="lazy" src="images/icon-image/fact2.png" alt="facts-img">
              </div>
              <div class="ts-facts-content">
                <h2 class="ts-facts-num"><span class="counterUp" data-count="647">0</span></h2>
                <h3 class="ts-facts-title">Staff Members</h3>
              </div>
          </div><!-- Col end -->

          <div class="col-md-3 col-sm-6 ts-facts mt-5 mt-md-0">
              <div class="ts-facts-img">
                <img loading="lazy" src="images/icon-image/fact3.png" alt="facts-img">
              </div>
              <div class="ts-facts-content">
                <h2 class="ts-facts-num"><span class="counterUp" data-count="4000">0</span></h2>
                <h3 class="ts-facts-title">Hours of Work</h3>
              </div>
          </div><!-- Col end -->

          <div class="col-md-3 col-sm-6 ts-facts mt-5 mt-md-0">
              <div class="ts-facts-img">
                <img loading="lazy" src="images/icon-image/fact4.png" alt="facts-img">
              </div>
              <div class="ts-facts-content">
                <h2 class="ts-facts-num"><span class="counterUp" data-count="44">0</span></h2>
                <h3 class="ts-facts-title">Countries Experience</h3>
              </div>
          </div><!-- Col end -->

        </div> <!-- Facts end -->
    </div>
    <!--/ Content row end -->
  </div>
  <!--/ Container end -->
</section><!-- Facts end -->

<section id="ts-team" class="ts-team">
  <div class="container">
    <div class="row text-center">
        <div class="col-lg-12">
          <h2 class="section-title">Quality Service</h2>
          <h3 class="section-sub-title">Professional Team</h3>
        </div>
    </div><!--/ Title row end -->

    <div class="row">
        <div class="col-lg-12">
          <div id="team-slide" class="team-slide">
              <div class="item">
                <div class="ts-team-wrapper">
                    <div class="team-img-wrapper">
                      <img loading="lazy" class="w-100" src="images/team/team1.jpg" alt="team-img">
                    </div>
                    <div class="ts-team-content">
                      <h3 class="ts-name">Nats Stenman</h3>
                      <p class="ts-designation">Chief Operating Officer</p>
                      <p class="ts-description">Nats Stenman began his career in construction with boots on the ground</p>
                      <div class="team-social-icons">
                          <a target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-google-plus"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-linkedin"></i></a>
                      </div><!--/ social-icons-->
                    </div>
                </div><!--/ Team wrapper end -->
              </div><!-- Team 1 end -->

              <div class="item">
                <div class="ts-team-wrapper">
                    <div class="team-img-wrapper">
                      <img loading="lazy" class="w-100" src="images/team/team2.jpg" alt="team-img">
                    </div>
                    <div class="ts-team-content">
                      <h3 class="ts-name">Angela Lyouer</h3>
                      <p class="ts-designation">Innovation Officer</p>
                      <p class="ts-description">Nats Stenman began his career in construction with boots on the ground</p>
                      <div class="team-social-icons">
                          <a target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-linkedin"></i></a>
                      </div><!--/ social-icons-->
                    </div>
                </div><!--/ Team wrapper end -->
              </div><!-- Team 2 end -->

              <div class="item">
                <div class="ts-team-wrapper">
                    <div class="team-img-wrapper">
                      <img loading="lazy" class="w-100" src="images/team/team3.jpg" alt="team-img">
                    </div>
                    <div class="ts-team-content">
                      <h3 class="ts-name">Mark Conter</h3>
                      <p class="ts-designation">Safety Officer</p>
                      <p class="ts-description">Nats Stenman began his career in construction with boots on the ground</p>
                      <div class="team-social-icons">
                          <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-google-plus"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-linkedin"></i></a>
                      </div><!--/ social-icons-->
                    </div>
                </div><!--/ Team wrapper end -->
              </div><!-- Team 3 end -->

              <div class="item">
                <div class="ts-team-wrapper">
                    <div class="team-img-wrapper">
                      <img loading="lazy" class="w-100" src="images/team/team4.jpg" alt="team-img">
                    </div>
                    <div class="ts-team-content">
                      <h3 class="ts-name">Ayesha Stewart</h3>
                      <p class="ts-designation">Finance Officer</p>
                      <p class="ts-description">Nats Stenman began his career in construction with boots on the ground</p>
                      <div class="team-social-icons">
                          <a target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-google-plus"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-linkedin"></i></a>
                      </div><!--/ social-icons-->
                    </div>
                </div><!--/ Team wrapper end -->
              </div><!-- Team 4 end -->

              <div class="item">
                <div class="ts-team-wrapper">
                    <div class="team-img-wrapper">
                      <img loading="lazy" class="w-100" src="images/team/team5.jpg" alt="team-img">
                    </div>
                    <div class="ts-team-content">
                      <h3 class="ts-name">Dave Clarkte</h3>
                      <p class="ts-designation">Civil Engineer</p>
                      <p class="ts-description">Nats Stenman began his career in construction with boots on the ground</p>
                      <div class="team-social-icons">
                          <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-google-plus"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-linkedin"></i></a>
                      </div><!--/ social-icons-->
                    </div>
                </div><!--/ Team wrapper end -->
              </div><!-- Team 5 end -->

              <div class="item">
                <div class="ts-team-wrapper">
                    <div class="team-img-wrapper">
                      <img loading="lazy" class="w-100" src="images/team/team6.jpg" alt="team-img">
                    </div>
                    <div class="ts-team-content">
                      <h3 class="ts-name">Elton Joe</h3>
                      <p class="ts-designation">Site Supervisor</p>
                      <p class="ts-description">Nats Stenman began his career in construction with boots on the ground</p>
                      <div class="team-social-icons">
                          <a target="_blank" href="#"><i class="fab fa-facebook-f"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-twitter"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-google-plus"></i></a>
                          <a target="_blank" href="#"><i class="fab fa-linkedin"></i></a>
                      </div><!--/ social-icons-->
                    </div>
                </div><!--/ Team wrapper end -->
              </div><!-- Team 6 end -->

          </div><!-- Team slide end -->
        </div>
    </div><!--/ Content row end -->
  </div><!--/ Container end -->
</section>

{% endblock %}

nabhold/templates/base_ext.html
<!DOCTYPE html> 
{% load static bootstrap5 %}
{% if 'use_i18n'|bootstrap_setting %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% endif %}
<html lang="{{ LANGUAGE_CODE|default:'en_us' }}">

<head>

	<!-- Title -->
	<meta charset="utf-8">
	<!-- Mobile Specific Metas -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Construction Html5 Template">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
	<meta name=author content="Themefisher">
	<meta name=generator content="Themefisher Constra HTML Template v1.0">

	<title>{% block title %} nabhold {% endblock %} | Nabusiu Holdings </title>
	<!-- Favicon  -->
	<link rel="icon" type="image/png" href="images/favicon.png">

	<!-- CSS, Fonts, and Icons   -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
		crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
		integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"
		integrity="sha512-NhSC1YmyruXifcj/KFRWoC561YpHpc5Jtzgvbuzx5VozKpWvQ+4nXhPdFgmx8xqexRcpAglTj9sIBWINXa8x5w=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
	<!-- Google fonts-->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
		rel="stylesheet" />
	<link
		href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
		rel="stylesheet" />
	<link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
		rel="stylesheet" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link
		href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;700;800&family=Poppins&display=swap"
		rel="stylesheet">
	{% bootstrap_css %}
	<!-- Bootstrap -->
	<link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/animate-css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/slick/slick.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/slick/slick-theme.css' %}">
	<link rel="stylesheet" href="{% static 'assets/plugins/colorbox/colorbox.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
	{% if 'javascript_in_head'|bootstrap_setting %}
	{% bootstrap_javascript %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/all.min.js"
		integrity="sha512-naukR7I+Nk6gp7p5TMA4ycgfxaZBJ7MO5iC3Fp6ySQyKFHOGfpkSZkYVWV5R7u7cfAicxanwYQ5D1e17EfJcMA=="
		crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	{% endif %}

	{% block extra_head %}{% endblock %}
</head>

<body>
	<div class="body-inner">
		{% block before_content %} 
		<header>
			<!-- Header start -->
			<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
				<!-- Navbar Brand-->
				<div class="container-fluid">
					<a class="navbar-brand ps-3" href="{% url 'main:home'%}">Nabhold</a>
					<!-- Sidebar Toggle-->
					<button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!">
						<i class="fas fa-bars"></i>
					</button>
					<!-- Navbar Search-->
					<form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
						<div class="input-group">
							<input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..."
								aria-describedby="btnNavbarSearch" />
							<button class="btn btn-primary border border-radius-0" id="btnNavbarSearch" type="button">
								<i class="fas fa-search"></i>
							</button>
						</div>
					</form>
					<!-- Navbar-->
					<ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
						{% if request.user.is_authenticated %} 
						<li class="nav-item dropdown">
							<span class="bg-secondary"> Hello {{ request.user.first_name|default:request.user.username }} </span>
							<a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
								aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
							<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
								<li><a class="dropdown-item" href="#!">Settings</a></li>
								<li><a class="dropdown-item" href="#!">Activity Log</a></li>
								<li>
									<hr class="dropdown-divider" />
								</li>
								<li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
							</ul>
						</li>
						{% endif %}
					</ul>
				</div>
			</nav>
			<div id="layoutSidenav">
				<div id="layoutSidenav_nav">
					<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
						<div class="sb-sidenav-menu">
							<div class="nav">
								<div class="sb-sidenav-menu-heading">Core</div>
								<a class="nav-link" href="index.html">
									<div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
									Dashboard
								</a>
								<div class="sb-sidenav-menu-heading">Interface</div>
								<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts"
									aria-expanded="false" aria-controls="collapseLayouts">
									<div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
									Layouts
									<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
								</a>
								<div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
									data-bs-parent="#sidenavAccordion">
									<nav class="sb-sidenav-menu-nested nav">
										<a class="nav-link" href="layout-static.html">Static Navigation</a>
										<a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
									</nav>
								</div>
								<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"
									aria-expanded="false" aria-controls="collapsePages">
									<div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
									Pages
									<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
								</a>
								<div class="collapse" id="collapsePages" aria-labelledby="headingTwo"
									data-bs-parent="#sidenavAccordion">
									<nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
										<a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
											data-bs-target="#pagesCollapseAuth" aria-expanded="false"
											aria-controls="pagesCollapseAuth">
											Authentication
											<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
										</a>
										<div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne"
											data-bs-parent="#sidenavAccordionPages">
											<nav class="sb-sidenav-menu-nested nav">
												<a class="nav-link" href="login.html">Login</a>
												<a class="nav-link" href="register.html">Register</a>
												<a class="nav-link" href="password.html">Forgot Password</a>
											</nav>
										</div>
										<a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
											data-bs-target="#pagesCollapseError" aria-expanded="false"
											aria-controls="pagesCollapseError">
											Error
											<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
										</a>
										<div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne"
											data-bs-parent="#sidenavAccordionPages">
											<nav class="sb-sidenav-menu-nested nav">
												<a class="nav-link" href="401.html">401 Page</a>
												<a class="nav-link" href="404.html">404 Page</a>
												<a class="nav-link" href="500.html">500 Page</a>
											</nav>
										</div>
									</nav>
								</div>
								<div class="sb-sidenav-menu-heading">Addons</div>
								<a class="nav-link" href="charts.html">
									<div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
									Charts
								</a>
								<a class="nav-link" href="tables.html">
									<div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
									Tables
								</a>
							</div>
						</div>
						<div class="sb-sidenav-footer">
							{% if request.user.is_authenticated %}
							<div class="small">Logged in as:</div>
							{{ request.user.first_name|default:request.user.username }} {{ request.user.last_name|default:request.user.username }}
							{% endif %}
						</div>
					</nav>
				</div>
		</header>
		{% endblock %}

		{% block sidebar%}
		<div id="layoutSidenav_content">
			<main>
				{% block content %} {% endblock %}
			</main>
		{% endblock %}
		



		<footer id="footer" class="footer bg-overlay">
			{% block footer_content %} 
			{% endblock %}

			<div class="copyright">
				<div class="container">
					<div class="row text-center">
						<div class="col-md-6">
							<div class="copyright-info text-sm text-left">
								<span>Copyright &copy;
									<script>
										document.write(new Date().getFullYear())
									</script> Nabhold | A member of <a href="https://nabhold.com"> Nabusiu Holdings </a> | All rights
									reserved.</a>
								</span>
							</div>
						</div>

						<div class="col-md-6">
							<div class="footer-menu text-center text-md-right">
								<ul class="list-unstyled text-right">
									<li><a href="{% url 'main:about' %}">About</a></li>
									<li><a href="{% url 'main:team' %}">Our people</a></li>
									<li><a href="{% url 'main:about' %}">Faq</a></li>
									<li><a href="{% url 'blog:articles' %}">Blog</a></li>
									<li><a href="{% url 'main:about' %}">Pricing</a></li>
								</ul>
							</div>
						</div>
					</div><!-- Row end -->

					<div id="back-to-top" data-spy="affix" data-offset-top="10" class="back-to-top position-fixed">
						<button class="btn btn-primary" title="Back to Top">
							<i class="fa fa-angle-double-up"></i>
						</button>
					</div>

				</div><!-- Container end -->
			</div>

			<!-- Copyright end -->
		</footer><!-- Footer end -->

		{% if not 'javascript_in_head'|bootstrap_setting %}
		{% bootstrap_javascript %}
		{% endif %}

		{% block bootstrap5_extra_script %}
		<!-- Javascript Files  -->
		<script src="plugins/jQuery/jquery.min.js"></script>
		<script src="plugins/bootstrap/bootstrap.min.js" defer></script>
		<script src="plugins/slick/slick.min.js"></script>
		<script src="plugins/slick/slick-animation.min.js"></script>
		<script src="plugins/colorbox/jquery.colorbox.js"></script>
		<script src="plugins/shuffle/shuffle.min.js" defer></script>


		<!-- Google Map API Key-->
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
			defer></script>
		<script src="plugins/google-map/map.js" defer></script>
		<script src="js/script.js"></script>
		{% endblock %}
	</div><!-- Body inner end -->
</body>

</html>

nabhold/templates/pagination.html
{% load static bootstrap5 %}

<!--

    <nav>
    <div class="pagination {{ pagination_css_classes }}">
        <span class="page-item">
            {% if page.has_previous %}
            <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
            {% endif %}
        </span>
        <span class="page-item">
            <span class="page-link active">   Page {{ page.number }}  of {{ page.paginator.num_pages }}.</span>
        </span>
        <span class="page-item"></span>
            {% if page.has_next %}
            <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
            {% endif %}
        </span>
    </div>


</nav>
-->
<section class="section">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</section>